/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  Matches: () => import('#controllers/matches_controller'),
  Rounds: () => import('#controllers/rounds_controller'),
  Seasons: () => import('#controllers/seasons_controller'),
  Users: () => import('#controllers/users_controller'),
}
