/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  Seasons: () => import('#controllers/seasons_controller'),
  Users: () => import('#controllers/users_controller'),
}
